# Generated by Django 4.2.1 on 2023-06-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_admin_clearance_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('shift_type', models.CharField(max_length=10)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='inmate',
            name='gender',
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('CO_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('title', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=11)),
                ('salary', models.BigIntegerField()),
                ('password', models.CharField(max_length=8)),
                ('shift', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='login.shift')),
            ],
        ),
    ]
