# Generated by Django 4.2.1 on 2023-06-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_medical_conditions_medical_inmate_medical_cond'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charges',
            new_name='Charge',
        ),
        migrations.RenameModel(
            old_name='Medical_conditions',
            new_name='Medical_condition',
        ),
    ]
