# Generated by Django 4.2.1 on 2023-06-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_charges_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='CO_id',
            new_name='med_id',
        ),
        migrations.AlterField(
            model_name='co',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CO', to='login.shift'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='login.shift'),
        ),
    ]
