# Generated by Django 4.2.1 on 2023-06-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_co_id_medical_med_id_alter_co_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('CNIC', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('Visit_time', models.TimeField(blank=True)),
                ('Visit_date', models.DateTimeField(blank=True)),
                ('approval_status', models.BooleanField(blank=True)),
                ('relation_w_inmate', models.CharField(max_length=24)),
                ('contact_number', models.CharField(max_length=11)),
                ('Inmate_visting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.inmate')),
            ],
        ),
        migrations.AddField(
            model_name='inmate',
            name='cell',
            field=models.ForeignKey(blank=True, default='c3', on_delete=django.db.models.deletion.CASCADE, related_name='inhabitant', to='login.cell'),
        ),
    ]
