# Generated by Django 4.2.1 on 2023-06-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_cell_visitor_inmate_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmate',
            name='cell',
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
    ]
