# Generated by Django 4.2.1 on 2023-06-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_inmate_cell_delete_cell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
