# Generated by Django 4.2.1 on 2023-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_cell_visitor_inmate_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='Visit_time',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='Visit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
