# Generated by Django 4.2.1 on 2023-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_visitor_visit_time_alter_visitor_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='password',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
