# Generated by Django 4.2.1 on 2023-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_visitor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='approval_status',
            field=models.BooleanField(null=True),
        ),
    ]
