# Generated by Django 4.2.1 on 2023-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_visitor_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='title',
            new_name='Speciality',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_type',
        ),
        migrations.AddField(
            model_name='shift',
            name='ending_day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='starting_day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
