# Generated by Django 4.2.1 on 2023-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_med_visit_delete_medical_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmate',
            name='medical_cond',
        ),
        migrations.AlterField(
            model_name='med_visit',
            name='diagnosis',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Medical_condition',
        ),
    ]
