# Generated by Django 4.2.1 on 2023-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_co_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
