# Generated by Django 4.2.1 on 2023-06-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_inmate_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('program_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='inmate',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='login.education'),
        ),
    ]
