# Generated by Django 4.2.1 on 2023-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=32)),
                ('clearance_level', models.SmallIntegerField(max_length=1)),
                ('contact_number', models.IntegerField(max_length=11)),
                ('salary', models.BigIntegerField()),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('Inmate_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('arrival_date', models.DateField()),
                ('release_date', models.DateField()),
                ('Risk_level', models.SmallIntegerField(max_length=1)),
                ('charges', models.ManyToManyField(related_name='criminal', to='home.charges')),
            ],
        ),
    ]
