# Generated by Django 4.2.1 on 2023-05-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.RemoveField(
            model_name='inmate',
            name='charges',
        ),
        migrations.DeleteModel(
            name='Charges',
        ),
        migrations.DeleteModel(
            name='Inmate',
        ),
    ]
